version: '1'
services:
  flyway:
    image: flyway/flyway
    command: -url=jdbc:postgresql://psql:5432/${POSTGRES_DB} -user=$POSTGRES_USER -password=$POSTGRES_PASSWORD -connectRetries=60 migrate
    volumes:
      - ./sql:/flyway/sql
    depends_on:
      - psql
  psql:
    image: postgres:14.6
    restart: always
    environment:
      - POSTGRES_PASSWORD=${POSTGRES_PASSWORD}
      - POSTGRES_USER=${POSTGRES_USER}
      - POSTGRES_DB=${POSTGRES_DB}
    ports:
      - 11420:5432
    volumes:
      # map default postgres data directory to our local directory to persist after docker down
      - ./postgres-data:/var/lib/postgresql/data